name = "cb-lock-console"
compatibility_date = "2026-06-24"
main = "worker.js"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "cb-lock-db"
database_id = "5aaa9655-3d02-44a2-bab4-7c37dfa2de1b"
